const tutors = [
  {
    name: "Fatima Khan",
    email: "fatima.khan@example.com",
    phone: "03001234567",
    education: "MSc Biology - Karachi University",
    subject: "Biology",
    rating: "4.8",
    price: "1500",
    location: "Karachi",
    imageUrl: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg",
  },
  {
    name: "Ali Raza",
    email: "ali.raza@example.com",
    phone: "03012345678",
    education: "MA English - NUML",
    subject: "Language",
    rating: "4.7",
    price: "1000",
    location: "Islamabad",
    imageUrl: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
  },
  {
    name: "Ayesha Malik",
    email: "ayesha.malik@example.com",
    phone: "03111223344",
    education: "MPhil Chemistry - Punjab University",
    subject: "Chemistry",
    rating: "5.0",
    price: "2000",
    location: "Lahore",
    imageUrl: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg",
  },
  {
    name: "Usman Tariq",
    email: "usman.tariq@example.com",
    phone: "03451234567",
    education: "BS Mathematics - GCU Faisalabad",
    subject: "Math",
    rating: "4.9",
    price: "1800",
    location: "Faisalabad",
    imageUrl: "https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg",
  },
  {
    name: "Hira Sohail",
    email: "hira.sohail@example.com",
    phone: "03334445555",
    education: "BA Philosophy - BZU Multan",
    subject: "Philosophy",
    rating: "4.6",
    price: "1200",
    location: "Multan",
    imageUrl: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",
  },
  {
    name: "Zainab Noor",
    email: "zainab.noor@example.com",
    phone: "03216543210",
    education: "BS Physics - NUST",
    subject: "Physics",
    rating: "4.95",
    price: "1900",
    location: "Rawalpindi",
    imageUrl: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg",
  },
  {
    name: "Ahmed Javed",
    email: "ahmed.javed@example.com",
    phone: "03459998811",
    education: "MS IT - FAST",
    subject: "Computer",
    rating: "4.85",
    price: "1600",
    location: "Lahore",
    imageUrl: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
  },
  {
    name: "Sana Iqbal",
    email: "sana.iqbal@example.com",
    phone: "03099887766",
    education: "MSc Zoology - PU",
    subject: "Biology",
    rating: "4.7",
    price: "1400",
    location: "Gujranwala",
    imageUrl: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg",
  },
  {
    name: "Farhan Qureshi",
    email: "farhan.q@example.com",
    phone: "03123456789",
    education: "MPhil Physics - COMSATS",
    subject: "Physics",
    rating: "4.9",
    price: "1950",
    location: "Islamabad",
    imageUrl: "https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg",
  },
  {
    name: "Mehwish Tariq",
    email: "mehwish.tariq@example.com",
    phone: "03477889922",
    education: "BS English - UMT",
    subject: "Language",
    rating: "4.6",
    price: "1100",
    location: "Lahore",
    imageUrl: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg",
  },
  {
    name: "Imran Abbas",
    email: "imran.abbas@example.com",
    phone: "03222333444",
    education: "MS Math - LUMS",
    subject: "Math",
    rating: "5.0",
    price: "2200",
    location: "Karachi",
    imageUrl: "https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg",
  },
  {
    name: "Areeba Shah",
    email: "areeba.shah@example.com",
    phone: "03119998877",
    education: "BS Islamic Studies - IIUI",
    subject: "Islamic",
    rating: "4.8",
    price: "1000",
    location: "Islamabad",
    imageUrl: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",
  },
  {
    name: "Bilal Haider",
    email: "bilal.haider@example.com",
    phone: "03456667788",
    education: "MCS - PU",
    subject: "Computer",
    rating: "4.7",
    price: "1700",
    location: "Lahore",
    imageUrl: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
  },
  {
    name: "Maham Riaz",
    email: "maham.riaz@example.com",
    phone: "03214567890",
    education: "BS Urdu - UOL",
    subject: "Language",
    rating: "4.65",
    price: "1300",
    location: "Rawalpindi",
    imageUrl: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg",
  },
  {
    name: "Waleed Anwar",
    email: "waleed.anwar@example.com",
    phone: "03091112233",
    education: "MSc Chemistry - GCU",
    subject: "Chemistry",
    rating: "4.75",
    price: "1500",
    location: "Lahore",
    imageUrl: "https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg",
  },
  {
    name: "Laiba Asif",
    email: "laiba.asif@example.com",
    phone: "03453332211",
    education: "B.Ed - AIOU",
    subject: "Islamic",
    rating: "4.6",
    price: "1100",
    location: "Multan",
    imageUrl: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",
  },
  {
    name: "Adil Hussain",
    email: "adil.hussain@example.com",
    phone: "03034445566",
    education: "MBA - IBA Karachi",
    subject: "Business",
    rating: "4.9",
    price: "2100",
    location: "Karachi",
    imageUrl: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
  },
  {
    name: "Iqra Fatima",
    email: "iqra.fatima@example.com",
    phone: "03128889900",
    education: "MPhil History - UCP",
    subject: "History",
    rating: "4.68",
    price: "1350",
    location: "Lahore",
    imageUrl: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg",
  },
  {
    name: "Omar Zubair",
    email: "omar.zubair@example.com",
    phone: "03449997755",
    education: "BS Statistics - Quaid-e-Azam University",
    subject: "Math",
    rating: "4.85",
    price: "1850",
    location: "Islamabad",
    imageUrl: "https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg",
  },
  {
    name: "Maryam Siddique",
    email: "maryam.s@example.com",
    phone: "03107778899",
    education: "MS Psychology - Punjab University",
    subject: "Psychology",
    rating: "4.9",
    price: "2000",
    location: "Lahore",
    imageUrl: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg",
  },
];

export default tutors;
